export const TAURI_COMMANDS = {
  getStarCitizenVersions: "get_star_citizen_versions",
  getTranslations: "get_translations",
  loadTranslationsSelected: "load_translations_selected",
  saveTranslationsSelected: "save_translations_selected",
  isGameTranslated: "is_game_translated",
  isTranslationUpToDate: "is_translation_up_to_date",
  getTranslationBySetting: "get_translation_by_setting",
  initTranslationFiles: "init_translation_files",
  updateTranslation: "update_translation",
  uninstallTranslation: "uninstall_translation",
  getCacheInformations: "get_cache_informations",
  deleteFolder: "delete_folder",
  openCacheFolder: "open_cache_folder",
  clearCache: "clear_cache",
  getCharacterInformations: "get_character_informations",
  deleteCharacter: "delete_character",
  duplicateCharacter: "duplicate_character",
  openCharactersFolder: "open_characters_folder",
  getCharacters: "get_characters",
  downloadCharacter: "download_character",
  loadGamelogBlueprints: "load_gamelog_blueprints",
  getGamelogWatcherStatus: "get_gamelog_watcher_status",
  startGamelogWatcher: "start_gamelog_watcher",
  stopGamelogWatcher: "stop_gamelog_watcher",
  importBlueprintsFromLogbackups: "import_blueprints_from_logbackups",
  exportGamelogBlueprints: "export_gamelog_blueprints",
  loadGamelogWatcherConfig: "load_gamelog_watcher_config",
  saveGamelogWatcherConfig: "save_gamelog_watcher_config",
  loadBackgroundServiceConfig: "load_background_service_config",
  saveBackgroundServiceConfig: "save_background_service_config",
  setBackgroundServiceConfig: "set_background_service_config",
  startBackgroundService: "start_background_service",
  stopBackgroundService: "stop_background_service",
  isAutoStartupEnabled: "is_auto_startup_enabled",
  enableAutoStartup: "enable_auto_startup",
  disableAutoStartup: "disable_auto_startup",
  getLatestCommits: "get_latest_commits",
  fetchRsiNews: "fetch_rsi_news",
  saveThemeSelected: "save_theme_selected",
  loadThemeSelected: "load_theme_selected",
  openExternal: "open_external",
} as const;

export type TauriCommand = (typeof TAURI_COMMANDS)[keyof typeof TAURI_COMMANDS];
